Do not interrupt the current thread
Threads might get interrupted when stopped by the
'workflow-durable-task-step-plugin'. Such interruptions does not allow
fluency to properly flush the queued events in the buffer.
java.io.IOException: Failed to move retention buffer due to interruption

See interruptions in the 'workflow-durable-task-step-plugin' plugin.
https://github.com/jenkinsci/workflow-durable-task-step-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java#L392
https://github.com/jenkinsci/workflow-support-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/support/concurrent/Timeout.java#L86